# Generated by Django 5.2.11 on 2026-02-27 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('ordre', models.IntegerField(default=0, help_text="Ordre d'affichage dans la liste de courses")),
            ],
            options={
                'verbose_name': 'Catégorie ingrédient',
                'verbose_name_plural': 'Catégories ingrédients',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour_debut_semaine', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi'), ('dimanche', 'Dimanche')], default='samedi', max_length=20)),
                ('intervalle_min_jours', models.IntegerField(default=14, help_text='Nombre minimum de jours entre deux fois le même plat')),
                ('nb_plats_aimes_min', models.IntegerField(default=2, help_text='Nombre minimum de plats aimés par membre par semaine')),
                ('heure_midi', models.TimeField(default='12:30')),
                ('heure_soir', models.TimeField(default='19:00')),
                ('mot_de_passe_lecteur', models.CharField(default='famille', max_length=100)),
                ('sms_actif', models.BooleanField(default=False)),
                ('brevo_api_key', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Configuration',
            },
        ),
        migrations.CreateModel(
            name='ListeCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('validee', 'Validée'), ('archivee', 'Archivée')], default='brouillon', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Liste de courses',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('annee_naissance', models.IntegerField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('couleur', models.CharField(default='#3B82F6', help_text="Couleur hex pour l'affichage", max_length=7)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Membre',
                'ordering': ['prenom'],
            },
        ),
        migrations.CreateModel(
            name='SemaineMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(help_text='Date du premier jour de la semaine')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié')], default='brouillon', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('publie_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Semaine menu',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('unite', models.CharField(blank=True, help_text='g, kg, cl, ml, pièce, boîte...', max_length=20)),
                ('url_produit', models.URLField(blank=True, help_text='URL sur le site de courses (ex: courseu.com)')),
                ('achat_systematique', models.BooleanField(default=False, help_text='Toujours dans la liste de courses')),
                ('lie_a_plat', models.BooleanField(default=True, help_text='False = produit de fond (sel, beurre...) sans recette associée')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients', to='meals.categorieingredient')),
            ],
            options={
                'verbose_name': 'Ingrédient',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='ItemListeCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_libre', models.CharField(blank=True, max_length=200)),
                ('quantite', models.FloatField(blank=True, null=True)),
                ('unite', models.CharField(blank=True, max_length=20)),
                ('source', models.CharField(choices=[('plat', 'Ingrédient de plat'), ('systematique', 'Achat systématique'), ('suggestion', 'Suggestion (rupture probable)'), ('manuel', 'Ajout manuel')], default='manuel', max_length=20)),
                ('coche', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meals.ingredient')),
                ('liste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='meals.listecourses')),
            ],
            options={
                'verbose_name': 'Item liste de courses',
                'ordering': ['source', 'ingredient__categorie__ordre', 'ingredient__nom', 'nom_libre'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_achat', models.DateField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_achats', to='meals.ingredient')),
                ('liste_courses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meals.listecourses')),
            ],
            options={
                'ordering': ['-date_achat'],
            },
        ),
        migrations.CreateModel(
            name='CreneauPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('creneau', models.CharField(choices=[('midi', 'Midi'), ('soir', 'Soir')], max_length=10)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('membres_secours', models.ManyToManyField(blank=True, help_text='Membres qui mangent le plat de secours', to='meals.membre')),
            ],
            options={
                'verbose_name': 'Créneau planning',
                'ordering': ['date', 'creneau'],
            },
        ),
        migrations.CreateModel(
            name='Plat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='plats/')),
                ('temps_preparation', models.IntegerField(default=30, help_text='Durée en minutes')),
                ('ingredient_principal', models.CharField(choices=[('viande', 'Viande'), ('poisson', 'Poisson'), ('pates', 'Pâtes'), ('riz', 'Riz'), ('pommes_de_terre', 'Pommes de terre'), ('legumes', 'Légumes'), ('oeufs', 'Œufs'), ('pain', 'Pain'), ('pizza', 'Pizza'), ('soupe', 'Soupe'), ('salade', 'Salade'), ('autre', 'Autre')], default='autre', help_text='Utilisé pour éviter deux repas consécutifs similaires', max_length=30)),
                ('est_secours', models.BooleanField(default=False, help_text='Plat de secours (rapide, boîte de conserve…)')),
                ('est_obligatoire', models.BooleanField(default=False, help_text='Servi même si des membres le détestent — pas de plat de secours')),
                ('saison_debut', models.CharField(blank=True, help_text='Format MM-JJ, ex: 11-01', max_length=5)),
                ('saison_fin', models.CharField(blank=True, help_text='Format MM-JJ, ex: 03-31', max_length=5)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('en_attente', 'En attente de validation'), ('inactif', 'Inactif')], default='actif', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('propose_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plats_proposes', to='meals.membre')),
            ],
            options={
                'verbose_name': 'Plat',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='HistoriquePlat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('creneau_planning', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meals.creneauplanning')),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='meals.plat')),
            ],
            options={
                'verbose_name': 'Historique plat',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DemandeModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('preference', 'Changement de préférence'), ('nouveau_plat', 'Proposition de nouveau plat')], max_length=20)),
                ('ancienne_note', models.CharField(blank=True, choices=[('aime', 'Aime'), ('neutre', 'Neutre'), ('deteste', 'Déteste')], max_length=10)),
                ('nouvelle_note', models.CharField(blank=True, choices=[('aime', 'Aime'), ('neutre', 'Neutre'), ('deteste', 'Déteste')], max_length=10)),
                ('data_json', models.JSONField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('refusee', 'Refusée')], default='en_attente', max_length=20)),
                ('message_admin', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('traite_at', models.DateTimeField(blank=True, null=True)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='meals.membre')),
                ('plat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meals.plat')),
            ],
            options={
                'verbose_name': 'Demande de modification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='creneauplanning',
            name='plat_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creneaux_principal', to='meals.plat'),
        ),
        migrations.AddField(
            model_name='creneauplanning',
            name='plat_secours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creneaux_secours', to='meals.plat'),
        ),
        migrations.CreateModel(
            name='PlatIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_par_portion', models.FloatField(blank=True, null=True)),
                ('unite', models.CharField(blank=True, help_text="Remplace l'unité par défaut de l'ingrédient", max_length=20)),
                ('notes', models.CharField(blank=True, help_text='Ex: 1 ou 2 packs selon appétit', max_length=200)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.ingredient')),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plat_ingredients', to='meals.plat')),
            ],
            options={
                'verbose_name': 'Ingrédient du plat',
                'unique_together': {('plat', 'ingredient')},
            },
        ),
        migrations.AddField(
            model_name='plat',
            name='ingredients',
            field=models.ManyToManyField(through='meals.PlatIngredient', to='meals.ingredient'),
        ),
        migrations.AddField(
            model_name='listecourses',
            name='semaine',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liste_courses', to='meals.semainemenu'),
        ),
        migrations.AddField(
            model_name='creneauplanning',
            name='semaine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='meals.semainemenu'),
        ),
        migrations.CreateModel(
            name='CreneauActif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi'), ('dimanche', 'Dimanche')], max_length=20)),
                ('creneau', models.CharField(choices=[('midi', 'Midi'), ('soir', 'Soir')], max_length=10)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux_actifs', to='meals.config')),
            ],
            options={
                'verbose_name': 'Créneau actif',
                'ordering': ['jour', 'creneau'],
                'unique_together': {('config', 'jour', 'creneau')},
            },
        ),
        migrations.CreateModel(
            name='DisponibilitePlat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi'), ('dimanche', 'Dimanche')], max_length=20)),
                ('creneau', models.CharField(choices=[('midi', 'Midi'), ('soir', 'Soir')], max_length=10)),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites', to='meals.plat')),
            ],
            options={
                'verbose_name': 'Disponibilité plat',
                'unique_together': {('plat', 'jour', 'creneau')},
            },
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(choices=[('aime', 'Aime'), ('neutre', 'Neutre'), ('deteste', 'Déteste')], default='neutre', max_length=10)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='meals.membre')),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='meals.plat')),
            ],
            options={
                'verbose_name': 'Préférence',
                'unique_together': {('membre', 'plat')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='creneauplanning',
            unique_together={('semaine', 'date', 'creneau')},
        ),
    ]
