# Generated by Django 5.2.11 on 2026-02-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='coursesu_login',
            field=models.CharField(blank=True, help_text='Email de connexion coursesu.com', max_length=200),
        ),
        migrations.AddField(
            model_name='config',
            name='coursesu_password',
            field=models.CharField(blank=True, help_text='Mot de passe coursesu.com (stocké en clair)', max_length=200),
        ),
    ]
