# Generated by Django 5.2.11 on 2026-02-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_config_coursesu_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='prix',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix unitaire indicatif (€)', max_digits=6, null=True),
        ),
    ]
