# Generated by Django 5.2.11 on 2026-02-27 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_add_prix_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL miniature du produit (import HAR)'),
        ),
    ]
