# Generated by Django 5.2.11 on 2026-02-28 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_add_image_url_ingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamillePlat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Famille de plat',
                'verbose_name_plural': 'Familles de plats',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='plat',
            name='famille',
            field=models.ForeignKey(blank=True, help_text='Regroupe les variantes (ex: Bolognaise). Le planning ne place pas deux variantes la même semaine.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variantes', to='meals.familleplat'),
        ),
    ]
