# Generated by Django 5.2.11 on 2026-02-28 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_add_famille_plat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plat',
            name='famille',
        ),
        migrations.AddField(
            model_name='creneauplanning',
            name='variant_choisi',
            field=models.ForeignKey(blank=True, help_text='Variant retenu pour ce créneau (ex: Penne dans une Bolognaise)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creneaux_variant', to='meals.ingredient'),
        ),
        migrations.AddField(
            model_name='historiqueplat',
            name='variant_choisi',
            field=models.ForeignKey(blank=True, help_text='Variant de cet ingrédient qui a été servi (ex: Penne)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique_comme_variant', to='meals.ingredient'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='nom_court',
            field=models.CharField(blank=True, help_text='Nom affiché dans le planning (ex: Penne). Si vide, le nom complet est utilisé.', max_length=100),
        ),
        migrations.AddField(
            model_name='platingredient',
            name='est_variant',
            field=models.BooleanField(default=False, help_text='Ingrédient interchangeable (ex: Penne/Farfalle). Le planning en choisit un par rotation.'),
        ),
        migrations.DeleteModel(
            name='FamillePlat',
        ),
    ]
